const { Login, G_signup, admin, adminG_signup, forgot_password, forgot_admin_password, adminG_verification, adminG_changepassword, G_verification, search_business, search_appointment, search_appointment2, view_appointments, cancel_appointment, logout, view_profile, view_admin_profile } = require('../controller/GetRoute');
const { login, admin_login, P_signup, adminP_signup, adminP_verification, adminP_changepassword, P_verification, P_changepassword, book_appointment, change_pass, change_prof, contactUs_req, change_pass_admin, change_admin_prof } = require('../controller/PostRoute');
const { Home, fetch_admins, Update, About, Contact, Members, BookApp, ViewApp, appointment, User_Profile, Admin_Home, Admin_About, Admin_Contact, Admin_Members, Admin_Profile } = require('../controller/LoginP');
const router = require('express').Router();

router.get('/', Login);
router.get('/signup', G_signup);
router.get('/admin', admin);
router.get('/admin_signup', adminG_signup);
router.get('/forgot-admin-password', forgot_admin_password);
router.get('/admin_changepassword', adminG_changepassword);
router.get('/admin_verification', adminG_verification);
router.get('/forgot-password', forgot_password);
router.get('/verification', G_verification);
router.get('/search-business', search_business);
router.get('/search-appointment', search_appointment);
router.get('/search-appointment2', search_appointment2);
router.get('/view-appointments', view_appointments);
router.put('/cancel-appointment/:id', cancel_appointment);
router.get('/Home', Home);
router.get('/appointments', appointment);
router.get('/About', About);
router.get('/Contact', Contact);
router.get('/Members', Members);
router.get('/Admin_Home', Admin_Home);
router.get('/Admin_About', Admin_About);
router.get('/Admin_Contact', Admin_Contact);
router.get('/Admin-Profile', Admin_Profile);
router.get('/Admin_Members', Admin_Members);
router.get('/BookApp', BookApp);
router.get('/ViewApp', ViewApp);
router.get('/User-Profile', User_Profile);
router.get('/logout', logout);
router.get('/view-profile', view_profile);
router.get('/view-admin-profile', view_admin_profile);

router.post('/Home', login);
router.post('/signup', P_signup);
router.post('/admin_login', admin_login);
router.post('/Info', fetch_admins);
router.post('/update-appointment', Update);
router.post('/admin_signup', adminP_signup);
router.post('/admin_changepassword', adminP_changepassword);
router.post('/admin_verification', adminP_verification);
router.post('/verification', P_verification);
router.post('/changepassword', P_changepassword);
router.post('/book-appointment', book_appointment);
router.post('/change-pass', change_pass);
router.post('/change-pass-admin', change_pass_admin);
router.post('/change-prof', change_prof);
router.post('/change-admin-prof', change_admin_prof);
router.post('/contactUs-req', contactUs_req);

module.exports = router;
